pkgs:
''
set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:RGB"
set -g status-position top

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -g @catppuccin_window_text " #{=|-25|..:pane_current_path} - #W"
set -g @catppuccin_window_current_text " #{=|-25|..:pane_current_path} - #W"

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'

run ${pkgs.tmuxPlugins.catppuccin}/share/tmux-plugins/catppuccin/catppuccin.tmux

set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
set -g status-left ""
''
