name: "Build Packages"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v3.21.8
      - uses: DeterminateSystems/magic-nix-cache-action@v14

      - run: |
          mkdir -p nix-archive

          nix build .#plasma-final
          nix copy --to file://$PWD/nix-archive $(readlink result)
          nix build .#plasma-prev
          nix copy --to file://$PWD/nix-archive $(readlink result)

      - uses: actions/upload-artifact@v4
        with:
          name: nix-packages
          path: ./nix-archive

